### ISSUE TITLE
Unable to view multiple scenes from .czi file

### ISSUE THREAD

**Issue by wonicorn** [JingyiGF/HERBS#56]
Hi, 

I have been trying to load .czi image files with multiple scenes but have only been able to load one scene at a time and can't access the other scenes while in HERBS. I read the cookbook and pressed the "Load ALL Scenes" button before loading my images, but the scene slider never appeared. Is there anything I might be missing, or is there something else I should try in regard to the histological images?

Thank you!

**Comment by JingyiGF** [comment]
Hi, Thank you for reporting this. I assume you have already tested your .czi file using other softwares so that you are sure there are multiple scenes in your file. HERBS only supports one scene to be read to hisological window. The purpose to do so is because HERBS was aiming for a registration tool rather than a histological viewer. Usually there are multiple scenes saved in users histological images, when HERBS load these scenes from the file to python. It can load one scene and then load another one when user asks it to do so. Or it can load all scenes at once so that all scenes can be saved as arrays ("Load all scenes"). But no matter users choose to load one scene a time or load all scenes at once, users can view only scene at a time. So you did not miss anything. It is designed to be like that.

But if the scene slider never appeared and you are sure there are multiple scenes, then it is a problem. If you want me to debug it, you have to share your file in some way. Or you can do it yourself,

from aicspylibczi import CziFile
czi = CziFile(czi_path) # where czi_path is the path to your czi file
print(czi.dims) # this is czi info
print(czi.get_dims_shape()) # this is dimension
print(czi.is_mosaic()) # check if mosaic
print(czi.pixel_type) # check pixel_type

if you return me the info, I can check if something I did no cover in the code. I think if something is missing in the code, it probably never happened with the czi files in our group.

**Comment by wonicorn** [comment]
Hi, 

I am 100% certain that the .czi has multiple scenes. I tried loading one of my files just now, and I noticed that the scene slider was present before I uploaded my images, but disappeared as soon as the image had loaded (even though I had selected load all scenes). 

Here is some more information about the files based on the code you provided:
<img width="517" alt="Screenshot 2024-01-30 at 6 59 49 PM" src="https://github.com/JingyiGF/HERBS/assets/140971083/3aa35cc6-a156-4e9d-8f23-5dc4e0ee960c">

**Comment by JingyiGF** [comment]
Hi, from the info you provided. There is only scene saved in the data. len(czi.get_dims_shape()) is the number of scene in our case. Could you please provide a sceenshot after you load the czi file into HERBS?

**Comment by wonicorn** [comment]
Hmm... I could view multiple scenes in the .czi file in another imaging software - I'm not sure why this is happening.

Here's a screen shot of the image loaded into HERBS:
<img width="1212" alt="Screenshot 2024-01-31 at 10 24 07 AM" src="https://github.com/JingyiGF/HERBS/assets/140971083/e2fb6bc3-387c-46fe-b13c-2d55abc17902">

**Comment by wonicorn** [comment]
Actually, I think that 'S': {0,4} might mean that the file has 0 to 4 scenes.

The documentation for get_dims_shape() seems to indicate that is the case: https://allencellmodeling.github.io/aicspylibczi/aicspylibczi.html#aicspylibczi.CziFile.get_dims_shape

**Comment by JingyiGF** [comment]
Not entirely correct. The data you printed, means you have 4 scenes saved together. What we have seen is when you have multi-scene, you will see something like this{‘S’: (0, 1), ‘T’: (0,8), ‘X’: (0, 475), ‘Y’: (0, 325), ‘Z’: (0, 4)}, {‘S’: (1, 2), ‘T’: (0,6), ‘X’: (0, 475), ‘Y’: (0, 325), ‘Z’: (0, 4)}, {‘S’: (2, 3), ‘T’: (0,7), ‘X’: (0, 475), ‘Y’: (0, 325), ‘Z’: (0, 4)},You can see there are 3 scenes and the first one has S:(0,1), second S:(1,2), and so on. Very strange indeed. Can you screenshot what shows in other app?Sent from my iPhoneOn 31 Jan 2024, at 16:57, wonicorn ***@***.***> wrote:﻿
Actually, I think that 'S': {0,4} might mean that the file has 0 to 4 scenes.
The documentation for get_dims_shape() seems to indicate that is the case: https://allencellmodeling.github.io/aicspylibczi/aicspylibczi.html#aicspylibczi.CziFile.get_dims_shape

**Comment by JingyiGF** [comment]
Not entirely correct. The data you printed, means you have 4 scenes saved together. What we have seen is when you have multi-scene, you will see something like this

{‘S’: (0, 1), ‘T’: (0,8), ‘X’: (0, 475), ‘Y’: (0, 325), ‘Z’: (0, 4)}, {‘S’: (1, 2), ‘T’: (0,6), ‘X’: (0, 475), ‘Y’: (0, 325), ‘Z’: (0, 4)}, {‘S’: (2, 3), ‘T’: (0,7), ‘X’: (0, 475), ‘Y’: (0, 325), ‘Z’: (0, 4)},

You can see there are 3 scenes and the first one has S:(0,1), second S:(1,2), and so on. 

Very strange indeed. Can you screenshot what shows in other app?

**Comment by wonicorn** [comment]
Hi, sorry for the late reply!

Here's a screenshot of what appears in the other app:
<img width="1107" alt="Screenshot 2024-01-31 at 3 26 55 PM" src="https://github.com/JingyiGF/HERBS/assets/140971083/5b11ab65-68dd-496a-b0e4-50351f0a4c9f">

The scene slider is on the bottom left.

**Comment by JingyiGF** [comment]
Different scenes correspond to different image when you drag the slider? Would be possible to share the file?

**Comment by JingyiGF** [comment]
Could you please screen shot the same scene?

**Comment by JingyiGF** [comment]
I think I see the problem now. Thanks for the screenshots. I never experienced the same type of scanning you have. Very interesting.

**Comment by wonicorn** [comment]
Hi, thank you again for your help!

I will try it now and let you know you it goes.

**Comment by JingyiGF** [comment]
Sorry, sorry, could you please try 0.2.8?

**Comment by skrigel** [comment]
Hi, 

I updated HERBS and tried uploading the image file, but it failed to load this time.
<img width="853" alt="Screenshot 2024-02-01 at 3 15 37 PM" src="https://github.com/JingyiGF/HERBS/assets/140971083/c724a29b-c96f-4d28-80d6-26658461e5f0">

**Comment by JingyiGF** [comment]
Would you mind sharing this file with me? Jingyi.g.fuglstad@gmail.com. You can find my personal email on GitHub webpage as well. It will be easier for me to debug. 

Any error message printed out in Python console?

**Comment by wonicorn** [comment]
Hi, just saw your updated message - will try 0.2.8

**Comment by skrigel** [comment]
Hi, I am sending you the file now. There was no error message printed on the Python console.

**Comment by JingyiGF** [comment]
BTW, did you try 0.2.7 or 0.2.8? Could you please help me to check?

**Comment by JingyiGF** [comment]
It’s late in the evening, I have to sleep now. I will check tomorrow. Thank you for the help!

**Comment by skrigel** [comment]
I tried updating herbs an additional time and I was able to view all 4 of the scenes!

 I tried sending the .czi file, but it may have been too large to send over email

Thank you for all of your help and great work!

**Comment by JingyiGF** [comment]
Hi, great it works now. Thank you for the feedback. I didnt receive the data, I would guess the data is so big and server blocked it. Anyway, I dont have to have it since everything works now :-) 

Thank you for the interesting data format so that I can correct my understanding on saving format. I am not an expert of it. Please let me know if there is other bugs in data loading. I am more than happy to fix the bugs.
