### ISSUE TITLE
"Please pre-process the raw data of your desired atlas"

### ISSUE THREAD

**Issue by ishiangoli** [JingyiGF/HERBS#7]
Hello,

I am currently running HERBS on a windows 10 computer and followed the instructions for downloading the Waxholm Rat Atlas (downloading and processing). When I try to load the atlas, I receive a message in the bottom left corner saying "please pre-process the raw data of your desired atlas". I was wondering if I have missed something?

**Comment by JingyiGF** [comment]
Hi, Thank you for the feedback. I wonder if you pre-processed the atlas after downloaded it? After successfully processing, you should have 'atlas_label.pkl', 'atlas_pre_made.pkl', 'contour_pre_made.pkl', 'segment_pre_made.pkl', 'atlas_meshdata.pkl', 'atlas_small_meshdata.pkl' and a folder called 'meshes' created in the folder where you save the downloaded atlas raw data. Could you please check if you have them? Or missing any? If you do not process the downloaded raw data or there is some files missing, please use the the Waxholm downloader to process the raw data.

**Comment by ishiangoli** [comment]
Hi, I can confirm I have all of those files after processing yet I still get this error message

**Comment by mdiamantaki** [comment]
Actually, this is the same problem I have. After selecting the folder with the atlas, nothing is loaded, status bar says 'please pre-process the raw data..' and no error in the python console (which stays still busy though).

**Comment by JingyiGF** [comment]
I am not sure you have the same issue. As the atlas for you Maria, is not finished processing. So there will is missing files, HERBS will always say you have to pre-process data.

**Comment by JingyiGF** [comment]
For the Waxholm Rat atlas, all the downloaded and processed files are listed in the screenshot. Hope this helps a bit :-)
<img width="424" alt="Screenshot 2022-09-28 at 15 06 55" src="https://user-images.githubusercontent.com/64961126/192786301-7b1b340d-3cdd-45cf-846d-c0ee5ca9f2b9.png">

**Comment by ishiangoli** [comment]
Hi Jingyi, thank you for sending this over, it looks like my files were downloaded and processed differently. They did not download with .pkl and the excel file in your picture is also missing from mine. I also have another file titled "WHS_SD_rat_atlas_v4"

**Comment by JingyiGF** [comment]
Let me check a bit first. Will update you later today :-)

**Comment by JingyiGF** [comment]
Hi, I downloaded and processed the waxholm rat atlas from the very beginning and it went fine. I could not re-produce the same problem as you have. The files I have are listed as in screenshot. The downloaded ones are the 4 whose name starting with 'WHS'. All pickle files and sub-folders are obtained after process. You can see files, time and size in the screenshot also. 

<img width="676" alt="Screenshot 2022-09-28 at 20 41 56" src="https://user-images.githubusercontent.com/64961126/192863022-14edc20e-911c-41b6-9a71-5db3b899948c.png">

My suggestion is
1. check which version of HERBS you are using. and update it to at least 0.0.14 if you install from PyPI or use the code on GitHub.
2. go to 'Atlas' menu -> 'Download Waxholm Rat Atlas' and download and process the atlas from the very beginning.

<img width="287" alt="Screenshot 2022-09-28 at 20 43 15" src="https://user-images.githubusercontent.com/64961126/192863283-b31a3280-cd03-4c62-b1bf-8d893b286a90.png">

It will be much easier for me to think where the bug is if you could show some screenshot about the problem. Many thanks.

**Comment by ishiangoli** [comment]
Hi, just an update on this. I installed HERBS using anaconda instead of Pycharm and had no issues, works perfectly :)

**Comment by JingyiGF** [comment]
Thanks for the updating. Then I will close this issue :-) you are always welcome to open a new issue when there is problems.
